---

- name: "Start EPNs"
  hosts: epn_nodes
  tasks:

    - name: "start epn nodes"
      shell: "./epn/epn --severity trace --verbosity high --id 1 --num-flp {{num_flp}} --channel-config name=1,type=pull,method=bind,address=tcp://*:5555,rateLogging=1 name=feedback,type=push,method=connect,address=tcp://192.168.1.4:5000 &"
      async: 60
      poll: 0
      args:
        chdir: /home/pi/O2-Balancer2/build
      register: epn_node
    
- name: "Start FLPs"
  hosts: flp_nodes
  serial:
        - "{{num_flp}}"
  tasks:
    
    - name: "start flp nodes"
      shell: "./flp/flp --severity trace --verbosity high --id 1 --bytes-per-message {{msg_size}} --channel-config name=broadcast,type=sub,method=connect,rateLogging=1,address=tcp://{{ansible_host}}:5005 &"
      async: 60
      poll: 0
      args:
        chdir: /home/pi/O2-Balancer2/build
      register: flp_node

- name: "Start ICN"
  hosts: controller_node
  tasks:
        
    - name: "start icn {{inventory_hostname}}"
      shell: "./icn/icn --control static --severity trace --verbosity high --id 1 --rate 50 --channel-config name=broadcast,type=pub,method=bind,rateLogging=0,address=tcp://*:5005 name=feedback,type=pull,method=bind,rateLogging=0,address=tcp://*:5000 &"
      async: 60
      poll: 5
      args:
        chdir: /home/pi/O2-Balancer2/build
      register: icn_node
