---

- name: "Reboot Raspberry PIs"
  hosts: all
  become: yes

  tasks:
    - name: reboot {{ansible_hostname}}
      shell: shutdown -r +1
      register: reboot

    - debug: 
        var: reboot.stdout_lines
